import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Link from 'next/link'
import Route from 'next/router';

import About from './about'

export default function Home() {

  function gotoA(){
    Route.push("/pageA")
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Study_01</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <Link  href="/pageA"><a>PageA</a></Link>
        </h1>

        <h1 className={styles.title}>
          Welcome to <Link  href="/pageB"><a>PageB</a></Link>
        </h1>

        <About>组件测试</About>

        <button onClick={gotoA}>去pageA</button>

      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
